#pragma once

namespace yasli{

enum BinaryNode {
  BINARY_NODE_BOOL,
  BINARY_NODE_STRING,
  BINARY_NODE_BYTE,
  BINARY_NODE_SBYTE,
  BINARY_NODE_INT16,
  BINARY_NODE_UINT16,
  BINARY_NODE_INT32,
  BINARY_NODE_UINT32,
  BINARY_NODE_INT64,
  BINARY_NODE_UINT64,
  BINARY_NODE_FLOAT,
  BINARY_NODE_DOUBLE,
  BINARY_NODE_POINTER = 0xfd,
  BINARY_NODE_CONTAINER = 0xfe,
  BINARY_NODE_STRUCT = 0xff
};

}
